
# Note - these tokens are generated using the following commands that should be run in the API directory.

# An AuthenticatedEmployee has no special roles.
# dotnet user-jwts create -n joe@company.com 
@AuthenticatedEmployeeToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImpvZUBjb21wYW55LmNvbSIsInN1YiI6ImpvZUBjb21wYW55LmNvbSIsImp0aSI6IjE5ZDk1Yjc0IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDoxMzM3IiwibmJmIjoxNzYyNzkyMDIwLCJleHAiOjE3NzA3NDA4MjAsImlhdCI6MTc2Mjc5MjAyMiwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.V9PRaKX6HT_lNZ43bo5QpHAoGx08gIFw4qKBStuVplQ

# An AuthenticatedSoftwareCenterEmployee has the SoftwareCenter role.
# dotnet user-jwts create -n sue@company.com --role SoftwareCenter    
@AuthenticatedSoftwareCenterEmployeeToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InN1ZUBjb21wYW55LmNvbSIsInN1YiI6InN1ZUBjb21wYW55LmNvbSIsImp0aSI6ImMwZDllZTQ0Iiwicm9sZSI6IlNvZnR3YXJlQ2VudGVyIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDoxMzM3IiwibmJmIjoxNzYyNzkyMDYxLCJleHAiOjE3NzA3NDA4NjEsImlhdCI6MTc2Mjc5MjA2MiwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.f_JMiiin5RC0Qcfv8bGvUMTzYfnEiRSm_0zO5feFjTs

# dotnet user-jwts create -n sue@company.com --role SoftwareCenter --role Manager
# An AuthenticatedSoftwareCenterManager has the SoftwareCenter and Manager roles.
@AuthenticateSoftwareCenterManagerToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InN1ZUBjb21wYW55LmNvbSIsInN1YiI6InN1ZUBjb21wYW55LmNvbSIsImp0aSI6IjkyZGFiM2ZkIiwicm9sZSI6WyJTb2Z0d2FyZUNlbnRlciIsIk1hbmFnZXIiXSwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDoxMzM3IiwibmJmIjoxNzYyNzkyMTA4LCJleHAiOjE3NzA3NDA5MDgsImlhdCI6MTc2Mjc5MjEwOSwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.2UOAMvw3FHxqTAF-p9_Izf4HGdP7bIx-3A4zJyRoxGk


###
# @prompt companyName
# @prompt companyUrl
# @prompt contactName
# @prompt contactEmail
# @prompt contactPhone
POST http://localhost:1337/vendors 
Authorization: {{AuthenticateSoftwareCenterManagerToken}}
Content-Type: application/json

{
  "name": "{{companyName}}",
  "url": "{{companyUrl}}",   
  "contact": {
    "name": "{{contactName}}",
    "email": "{{contactEmail}}",
    "phone": "{{contactPhone}}"
  }
}


### 
# @prompt vendorId
GET http://localhost:1337/vendors/{{vendorId}}
Authorization: {{AuthenticatedEmployeeToken}}

### 
GET http://localhost:1337/vendors 
Authorization: {{AuthenticatedEmployeeToken}}

